name: 破格音樂 Prog Records
favicon: null
layout_spectrum: 0.6179572388064116
typography_spectrum: 0.033122914377599955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2200763642322272
  lightness: 0.2068357919342816
  saturation: 0.5186865981668234
  rhythmicContrast: 0.8380633799824864
purpose: []
